#spring
spring:
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/caratacus
    username: caratacus
    password: caratacus
    driver-class-name: org.postgresql.Driver
#mybatis
mybatis-plus:
  mapper-locations: classpath:com/baomidou/mybatisplus/sample/sql/*Mapper.xml
  typeAliasesPackage: com.baomidou.mybatisplus.sample.entity
  global-config:
    id-type: 3
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#logging
logging:
  level: warn
